"""Make description_clean

Revision ID: 67a226f75c7d
Revises: 97a535f63f84
Create Date: 2025-10-28 23:24:26.601399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a226f75c7d'
down_revision: Union[str, None] = '97a535f63f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'description_clean',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'description_clean',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
