"""Make description_clean nullable

Revision ID: 97a535f63f84
Revises: 2bdf9767d08f
Create Date: 2025-10-28 23:21:57.667079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a535f63f84'
down_revision: Union[str, None] = '2bdf9767d08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'description_clean',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'description_clean',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
